export const bleedWrapper: string;
export const bleedBackground: string;
export const bleedMainContent: string;
export const gridParent: string;
export const gridAreaBottom: string;
export const title: string;
export const statCard: string;
export const number: string;
export const statement: string;
